### ISSUE TITLE
HelpWanted

### ISSUE THREAD

**Issue by undefined-moe** [bestvist/axial3d#1]
如果我希望其他组件自适应怎么办
它的绝对定位导致了我的其他组件覆盖在图片上方....
（而且我对于上级元素设置的text-align:center也挂了）
当前使用@vue/cli3.0
![image](https://user-images.githubusercontent.com/29992205/51538520-76dd9a80-1e8c-11e9-8c52-f02b50bffdeb.png)

热重载会导致奇怪的bug
![image](https://user-images.githubusercontent.com/29992205/51538388-15b5c700-1e8c-11e9-9e41-d7b8f03a5d9b.png)

```vue
<template>
  <div>
    <h1>Welcome</h1>
    <ma-novue id="homepageLogo"></ma-novue>
  </div>
</template>
<script>
import Axial3d from "axial3d";
export default {
  name: "homepage",
  created() {
    window.bus.$on("update", () => {
      this.$forceUpdate();
    });
  }
};
var options = {
  selector: "#homepageLogo",
  imgs: [
    {
      src: "https://bestvist.github.io/axial3d/public/demo1/bg.png",
      left: "50px",
      top: "10px"
    },
    {
      src: "https://bestvist.github.io/axial3d/public/demo1/2.png",
      left: "150px",
      top: "10px"
    },
    {
      src: "https://bestvist.github.io/axial3d/public/demo1/3.png",
      left: "50px",
      top: "300px"
    },
    {
      src: "https://bestvist.github.io/axial3d/public/demo1/4.png",
      left: "300px",
      top: "300px"
    }
  ],
  transform: "rotate"
};
setTimeout(()=>{var effect = new Axial3d(options)},1000);
</script>
```

**Comment by bestvist** [comment]
抱歉我没能及时看到问题。
这个插件是在选择元素进行3D效果，如果你想让其他元素自适应可以把它们放在元素外面。
如果做vue组件的话，应该是一个子组件，而不是所有元素的父级。
@masnn

**Comment by undefined-moe** [comment]
上述代码已经为子组件
架构如下:
Root
├上图组件
│└ma-novue
└mu-button

我所注册的no-vue组件仅仅包含所指定id的一个div标签，用途是防止父组件使用this.$forceUpdate()时导致渲染失效

以上方法执行之后，homepagelogo会使用position:fixed进行定位。这导致其后的元素会忽略其所占的空间。

同时，似乎3D组件没有被渲染在所指定的div标签中，而是插入在了同级目录，导致预设定的css失效。

**Comment by bestvist** [comment]
或许看下src/axial3d.js 具体的实现方法可以更清楚，在render方法中是通过`this.$el.appendChild($frag);`实现，在选择的元素内部尾部插入。可以尝试在ma-novue组件内部配置Axial3d呢？
